const routeMap = [
  { method: "GET", path: "/api/health", targetPath: "/api/health", service: "BUSINESS" },
  { method: "GET", path: "/api/docs", targetPath: "/api/docs", service: "BUSINESS" },

  // Businesses
  { method: "POST", path: "/businesses", targetPath: "/api/businesses", service: "BUSINESS" },
  { method: "GET", path: "/businesses", targetPath: "/api/businesses", service: "BUSINESS" },
  { method: "GET", path: "/businesses/archived", targetPath: "/api/businesses/archived", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId", targetPath: "/api/businesses/:businessId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId", targetPath: "/api/businesses/:businessId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/retire", targetPath: "/api/businesses/:businessId/retire", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/restore", targetPath: "/api/businesses/:businessId/restore", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/availability", targetPath: "/api/businesses/:businessId/availability", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/summary", targetPath: "/api/businesses/:businessId/summary", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/history", targetPath: "/api/businesses/:businessId/history", service: "BUSINESS" },

  // Schedules and temporary closures
  { method: "POST", path: "/businesses/:businessId/schedules", targetPath: "/api/businesses/:businessId/schedules", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/schedules", targetPath: "/api/businesses/:businessId/schedules", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/schedules/:scheduleId", targetPath: "/api/businesses/:businessId/schedules/:scheduleId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/schedules/:scheduleId", targetPath: "/api/businesses/:businessId/schedules/:scheduleId", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/temporary-closures", targetPath: "/api/businesses/:businessId/temporary-closures", service: "BUSINESS" },
  { method: "POST", path: "/businesses/:businessId/temporary-closures", targetPath: "/api/businesses/:businessId/temporary-closures", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/temporary-closures/:temporaryClosureId/finish", targetPath: "/api/businesses/:businessId/temporary-closures/:temporaryClosureId/finish", service: "BUSINESS" },

  // Product types
  { method: "POST", path: "/businesses/:businessId/product-types", targetPath: "/api/businesses/:businessId/product-types", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/product-types", targetPath: "/api/businesses/:businessId/product-types", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/product-types/archived", targetPath: "/api/businesses/:businessId/product-types/archived", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/product-types/:productTypeId", targetPath: "/api/businesses/:businessId/product-types/:productTypeId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/product-types/:productTypeId", targetPath: "/api/businesses/:businessId/product-types/:productTypeId", service: "BUSINESS" },
  { method: "DELETE", path: "/businesses/:businessId/product-types/:productTypeId", targetPath: "/api/businesses/:businessId/product-types/:productTypeId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/product-types/:productTypeId/retire", targetPath: "/api/businesses/:businessId/product-types/:productTypeId/retire", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/product-types/:productTypeId/restore", targetPath: "/api/businesses/:businessId/product-types/:productTypeId/restore", service: "BUSINESS" },

  // Products and catalog
  { method: "POST", path: "/businesses/:businessId/products", targetPath: "/api/businesses/:businessId/products", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/products", targetPath: "/api/businesses/:businessId/products", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/products/archived", targetPath: "/api/businesses/:businessId/products/archived", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/products/:productId", targetPath: "/api/businesses/:businessId/products/:productId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/products/:productId", targetPath: "/api/businesses/:businessId/products/:productId", service: "BUSINESS" },
  { method: "DELETE", path: "/businesses/:businessId/products/:productId", targetPath: "/api/businesses/:businessId/products/:productId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/products/:productId/retire", targetPath: "/api/businesses/:businessId/products/:productId/retire", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/products/:productId/restore", targetPath: "/api/businesses/:businessId/products/:productId/restore", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/products/:productId/hide", targetPath: "/api/businesses/:businessId/products/:productId/hide", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/products/:productId/show", targetPath: "/api/businesses/:businessId/products/:productId/show", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/catalog", targetPath: "/api/businesses/:businessId/catalog", service: "BUSINESS" },

  // Inventory
  { method: "GET", path: "/businesses/:businessId/inventory", targetPath: "/api/businesses/:businessId/inventory", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/inventory/products/:productId", targetPath: "/api/businesses/:businessId/inventory/products/:productId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/inventory/products/:productId/stock", targetPath: "/api/businesses/:businessId/inventory/products/:productId/stock", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/products/:productId/stock", targetPath: "/api/businesses/:businessId/products/:productId/stock", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/products/:productId/stock", targetPath: "/api/businesses/:businessId/products/:productId/stock", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/inventory-movements", targetPath: "/api/businesses/:businessId/inventory-movements", service: "BUSINESS" },

  // Orders
  { method: "POST", path: "/businesses/:businessId/orders", targetPath: "/api/businesses/:businessId/orders", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/orders", targetPath: "/api/businesses/:businessId/orders", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/orders/deliveries", targetPath: "/api/businesses/:businessId/orders/deliveries", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/orders/:businessOrderId", targetPath: "/api/businesses/:businessId/orders/:businessOrderId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/orders/:businessOrderId/status", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/status", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/orders/:businessOrderId/preparing", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/preparing", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/orders/:businessOrderId/ready-for-pickup", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/ready-for-pickup", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/orders/:businessOrderId/status-history", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/status-history", service: "BUSINESS" },
  { method: "POST", path: "/businesses/:businessId/orders/:businessOrderId/evaluate-cancellation-penalty", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/evaluate-cancellation-penalty", service: "BUSINESS" },
  { method: "POST", path: "/businesses/:businessId/orders/:businessOrderId/cancel", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/cancel", service: "BUSINESS" },

  // Deliveries
  { method: "GET", path: "/businesses/:businessId/orders/:businessOrderId/delivery", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/delivery", service: "BUSINESS" },
  { method: "POST", path: "/businesses/:businessId/orders/:businessOrderId/delivery", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/delivery", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/orders/:businessOrderId/delivery", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/delivery", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/orders/:businessOrderId/delivery/status-history", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/delivery/status-history", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/orders/:businessOrderId/delivery/fee-adjustments", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/delivery/fee-adjustments", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/orders/:businessOrderId/delivery/fee-adjustments/:deliveryFeeAdjustmentId", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/delivery/fee-adjustments/:deliveryFeeAdjustmentId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/orders/:businessOrderId/delivery/fee-adjustments/:deliveryFeeAdjustmentId/resolve", targetPath: "/api/businesses/:businessId/orders/:businessOrderId/delivery/fee-adjustments/:deliveryFeeAdjustmentId/resolve", service: "BUSINESS" },

  // Promotions
  { method: "POST", path: "/businesses/:businessId/promotion-requests", targetPath: "/api/businesses/:businessId/promotion-requests", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/promotion-requests", targetPath: "/api/businesses/:businessId/promotion-requests", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/promotion-requests/:promotionRequestId", targetPath: "/api/businesses/:businessId/promotion-requests/:promotionRequestId", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/promotions", targetPath: "/api/businesses/:businessId/promotions", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/promotions/:promotionReferenceId", targetPath: "/api/businesses/:businessId/promotions/:promotionReferenceId", service: "BUSINESS" },
  { method: "PATCH", path: "/businesses/:businessId/promotions/:promotionReferenceId/hide", targetPath: "/api/businesses/:businessId/promotions/:promotionReferenceId/hide", service: "BUSINESS" },

  // Metrics and support
  { method: "GET", path: "/metrics/daily", targetPath: "/api/metrics/daily", service: "BUSINESS" },
  { method: "GET", path: "/metrics/range", targetPath: "/api/metrics/range", service: "BUSINESS" },
  { method: "GET", path: "/metrics/summary", targetPath: "/api/metrics/summary", service: "BUSINESS" },
  { method: "POST", path: "/metrics/rebuild", targetPath: "/api/metrics/rebuild", service: "BUSINESS" },
  { method: "POST", path: "/promotions/requests", targetPath: "/api/promotions/requests", service: "BUSINESS" },
  { method: "GET", path: "/promotions/requests", targetPath: "/api/promotions/requests", service: "BUSINESS" },
  { method: "GET", path: "/promotions/requests/:promotionRequestId", targetPath: "/api/promotions/requests/:promotionRequestId", service: "BUSINESS" },
  { method: "PATCH", path: "/promotions/requests/:promotionRequestId/external-response", targetPath: "/api/promotions/requests/:promotionRequestId/external-response", service: "BUSINESS" },
  { method: "POST", path: "/promotions/references/sync", targetPath: "/api/promotions/references/sync", service: "BUSINESS" },
  { method: "GET", path: "/promotions/references", targetPath: "/api/promotions/references", service: "BUSINESS" },
  { method: "GET", path: "/promotions/sync-history", targetPath: "/api/promotions/sync-history", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/metrics/summary", targetPath: "/api/businesses/:businessId/metrics/summary", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/metrics/sales", targetPath: "/api/businesses/:businessId/metrics/sales", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/metrics/orders-by-status", targetPath: "/api/businesses/:businessId/metrics/orders-by-status", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/metrics/top-products", targetPath: "/api/businesses/:businessId/metrics/top-products", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/metrics/daily-growth", targetPath: "/api/businesses/:businessId/metrics/daily-growth", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/metrics/deliveries", targetPath: "/api/businesses/:businessId/metrics/deliveries", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/metrics/delivery-fee-adjustments", targetPath: "/api/businesses/:businessId/metrics/delivery-fee-adjustments", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/support/summary", targetPath: "/api/businesses/:businessId/support/summary", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/support/orders/:externalOrderCode", targetPath: "/api/businesses/:businessId/support/orders/:externalOrderCode", service: "BUSINESS" },
  { method: "GET", path: "/businesses/:businessId/support/orders/:externalOrderCode/delivery", targetPath: "/api/businesses/:businessId/support/orders/:externalOrderCode/delivery", service: "BUSINESS" },

  // Internal integrations
  { method: "POST", path: "/internal/business-orders/validate-and-reserve", targetPath: "/api/internal/business-orders/validate-and-reserve", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/confirm", targetPath: "/api/internal/business-orders/confirm", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/confirm-order", targetPath: "/api/internal/business-orders/confirm-order", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/release-reservation", targetPath: "/api/internal/business-orders/release-reservation", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/evaluate-cancellation-penalty", targetPath: "/api/internal/business-orders/evaluate-cancellation-penalty", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/cancel", targetPath: "/api/internal/business-orders/cancel", service: "BUSINESS" },
  { method: "GET", path: "/internal/business-orders/:externalOrderCode", targetPath: "/api/internal/business-orders/:externalOrderCode", service: "BUSINESS" },
  { method: "GET", path: "/internal/business-orders/:externalOrderCode/delivery", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/:externalOrderCode/delivery", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/delivery/link", targetPath: "/api/internal/business-orders/delivery/link", service: "BUSINESS" },
  { method: "GET", path: "/internal/business-orders/delivery/by-logistics-order/:externalLogisticsOrderCode", targetPath: "/api/internal/business-orders/delivery/by-logistics-order/:externalLogisticsOrderCode", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/delivery/update-status", targetPath: "/api/internal/business-orders/delivery/update-status", service: "BUSINESS" },
  { method: "PATCH", path: "/internal/business-orders/:externalOrderCode/delivery/assign-courier", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery/assign-courier", service: "BUSINESS" },
  { method: "PATCH", path: "/internal/business-orders/:externalOrderCode/delivery/status", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery/status", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/:externalOrderCode/delivery/fee-adjustments", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery/fee-adjustments", service: "BUSINESS" },
  { method: "GET", path: "/internal/business-orders/:externalOrderCode/delivery/fee-adjustments", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery/fee-adjustments", service: "BUSINESS" },
  { method: "PATCH", path: "/internal/business-orders/:externalOrderCode/delivery/fee-adjustments/:deliveryFeeAdjustmentId/resolve", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery/fee-adjustments/:deliveryFeeAdjustmentId/resolve", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/:externalOrderCode/delivery/apply-fee-adjustment", targetPath: "/api/internal/business-orders/:externalOrderCode/delivery/apply-fee-adjustment", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/delivery/fee-adjustments/request", targetPath: "/api/internal/business-orders/delivery/fee-adjustments/request", service: "BUSINESS" },
  { method: "GET", path: "/internal/business-orders/delivery/fee-adjustments/by-order/:externalOrderCode", targetPath: "/api/internal/business-orders/delivery/fee-adjustments/by-order/:externalOrderCode", service: "BUSINESS" },
  { method: "GET", path: "/internal/business-orders/delivery/fee-adjustments/by-logistics-order/:externalLogisticsOrderCode", targetPath: "/api/internal/business-orders/delivery/fee-adjustments/by-logistics-order/:externalLogisticsOrderCode", service: "BUSINESS" },
  { method: "POST", path: "/internal/business-orders/delivery/fee-adjustments/resolve", targetPath: "/api/internal/business-orders/delivery/fee-adjustments/resolve", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/availability", targetPath: "/api/internal/businesses/:businessId/availability", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/base-catalog", targetPath: "/api/internal/businesses/:businessId/base-catalog", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/active-promotions", targetPath: "/api/internal/businesses/:businessId/active-promotions", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/aggregated-metrics", targetPath: "/api/internal/businesses/:businessId/aggregated-metrics", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/reports/sales", targetPath: "/api/internal/businesses/:businessId/reports/sales", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/reports/attended-orders", targetPath: "/api/internal/businesses/:businessId/reports/attended-orders", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/reports/deliveries", targetPath: "/api/internal/businesses/:businessId/reports/deliveries", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/reports/delivery-fee-adjustments", targetPath: "/api/internal/businesses/:businessId/reports/delivery-fee-adjustments", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/orders/:externalOrderCode/support", targetPath: "/api/internal/businesses/:businessId/orders/:externalOrderCode/support", service: "BUSINESS" },
  { method: "GET", path: "/internal/businesses/:businessId/history-summary", targetPath: "/api/internal/businesses/:businessId/history-summary", service: "BUSINESS" },
  { method: "POST", path: "/internal/promotion-requests", targetPath: "/api/internal/promotion-requests", service: "BUSINESS" },
  { method: "POST", path: "/internal/promotions/sync", targetPath: "/api/internal/promotions/sync", service: "BUSINESS" },
  { method: "GET", path: "/internal/promotions/:externalPromotionId", targetPath: "/api/internal/promotions/:externalPromotionId", service: "BUSINESS" },
  { method: "POST", path: "/internal/promotions/report-operational-change", targetPath: "/api/internal/promotions/report-operational-change", service: "BUSINESS" },
];

module.exports = routeMap;
